services:
  fidexa_api:
    env_file:
      - ./.env
    image: fidexa_api:latest
    container_name: fidexa_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ./logs:/logs
      - ./certificates:/app/certificates
      - ./temp-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
      - Kestrel__Certificates__Default__Path=/app/certificates/certificate.pfx
      - Kestrel__Certificates__Default__Password=123
    networks:
      - docker_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - fidexa_api
    networks:
      - docker_network
    
networks:
  docker_network:
    driver: bridge