FROM grafana/loki:latest

# Copie o arquivo de configuração
COPY loki-config.yaml /etc/loki/local-config.yaml

# Exponha a porta
EXPOSE 3100

# Comando padrão
CMD ["-config.file=/etc/loki/local-config.yaml"]